spring:
  application:
    name: user-service   # must match config-repo file
  profiles:
    active: dev                  # ðŸ‘ˆ environment (dev / test / prod)
  config:
    import: optional:configserver:http://localhost:8888