spring:
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: INFO
    com.user.service: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0   # dev only (reduce in prod)
    export:
      enabled: true      # âœ… THIS enables tracing in Boot 4

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans